### ISSUE TITLE
[Chrome 46 (64-bit) / Windows 8.1] Game Non-functional After Non-Saved Load

### ISSUE THREAD

**Issue by omento** [voiddreamer/BotLandTracking#4]
I believe this bug requires the use of a new computer or browser that has never touched Bot Land before. Typically I'm on my laptop, but I'm home over break and on my desktop, which I've never used for the game.

* Load Game
* Open Blockly or JS Editor
* Hit the "Load" button (wanted to see if scripts were saved locally or server side)
* When Blockly or JS is closed, loading them up refuses to give proper graphical response
   * Blockly doesn't show the Hardware pane
   * JS Editor rescales the editor canvas
   * Chat does not work
   * After a while both functions refuse to open at all, leaving just the regular buttons visible
* Refresh of the page fixes the issue

Note: After the refresh, if there are no scripts saved, then the game will do exactly what happened before if the steps are followed again.

Vid of bug in action: https://youtu.be/_JcnLq5jvy8

**Comment by CaymonS** [comment]
[b]Reproduction[/b] can probably be done by clearing your cache.

Try opening the Developer Console (Ctrl-Shift-I) and click the console tab and see if any errors are coming in. It sounds like some your browser didn't get some required files or something to that nature ([i]It might have also been fixed by now[/i]). 

Be sure to post a screen shot if there are any errors!

**Comment by Adam13531** [comment]
I fixed this bug, but it won't be live until I redeploy, so wait a day or two. :)
