### ISSUE TITLE
[Chrome 46 / Windows 10] I can choose buffs even if I'm not logged in

### ISSUE THREAD

**Issue by isurakka** [voiddreamer/BotLandTracking#5]

**Comment by Adam13531** [comment]
Hey,

Thanks for posting this, but this is by design for right now. What's happening is there's no true title screen in Bot Land yet, so as soon as you're finished loading the page, you're thrown into Single Player Mode, where just like in Multiplayer, you're given the choice of a buff at the beginning of a match.

Eventually, you'll be on a title screen and you'll be able to choose between various modes, and then it would indeed be a bug if you were immediately presented with buff options.

Regardless, thanks for reporting this!
